ALTER TABLE `lucky_game`.`orders` 
ADD COLUMN `u_os` smallint UNSIGNED NULL DEFAULT 0 COMMENT '用户支付系统：0默认 1安卓 2苹果 3微信小程序网页订单' AFTER `explain`;

ALTER TABLE `lucky_game`.`distribution_settle_conf` 
ADD COLUMN `u_os` smallint UNSIGNED NULL DEFAULT 0 COMMENT '用户支付系统：0默认 1安卓 2苹果 3微信小程序网页订单' AFTER `desc`;

INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 1, 1, 1, 10, 'num', 0.7000, 7.0000, '房卡分佣一级档位', 1, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 2, 1, 11, 20, 'num', 0.6667, 12.0000, '房卡分佣二级档位', 1, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 3, 1, 21, 50, 'num', 0.6250, 25.0000, '房卡分佣三级档位', 1, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 4, 1, 51, 100, 'num', 0.5714, 40.0000, '房卡分佣四级档位', 1, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 5, 1, 101, 200, 'num', 0.5313, 68.0000, '房卡分佣五级档位', 1, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 6, 1, 201, 500, 'num', 0.5000, 150.0000, '房卡分佣六级档位', 1, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 7, 1, 501, 1000, 'num', 0.4545, 250.0000, '房卡分佣七级档位', 1, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 8, 1, 1001, 2000, 'num', 0.4000, 400.0000, '房卡分佣八级档位', 1, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 9, 1, 2001, 10000, 'num', 0.3333, 750.0000, '房卡分佣九级档位', 1, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 10, 1, 10001, 16000, 'num', 0.1429, 800.0000, '房卡分佣十级档位', 1, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 1, 2, 1, 1, 'amount', 0.5000, 0.0000, '农产品分佣', 1, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 1, 2, 1, 1, 'amount', 0.3000, 0.0000, '农产品分佣', 2, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 11, 1, 1, 6, 'num', 0.6000, 3.6000, '苹果端房卡分佣一级档位', 2, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 12, 1, 7, 18, 'num', 0.6000, 10.8000, '苹果端房卡分佣二级档位', 2, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 13, 1, 19, 30, 'num', 0.6000, 18.0000, '苹果端房卡分佣三级档位', 2, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 14, 1, 31, 68, 'num', 0.6000, 40.8000, '苹果端房卡分佣四级档位', 2, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 15, 1, 69, 128, 'num', 0.6000, 76.8000, '苹果端房卡分佣五级档位', 2, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 16, 1, 129, 198, 'num', 0.6000, 118.8000, '苹果端房卡分佣六级档位', 2, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 17, 1, 199, 328, 'num', 0.6000, 196.8000, '苹果端房卡分佣七级档位', 2, 0);
INSERT INTO `lucky_game`.`distribution_settle_conf` (`created`, `level`, `type`, `range_min`, `range_max`, `profit_condition`, `profit_ratio`, `profit_num`, `desc`, `u_os`, `updated`) VALUES (0, 18, 1, 329, 648, 'num', 0.6000, 388.8000, '苹果端房卡分佣八级档位', 2, 0);
