UPDATE `lucky_game`.`tournament_rewards` SET `round_type` = 1, `rank_start` = 1, `rank_end` = 20, `reward_content` = '[{\"award_ids\": [51, 86], \"ranking_end\": 1, \"final_ticket\": 1, \"ranking_start\": 1}, {\"award_ids\": [51, 87], \"ranking_end\": 3, \"final_ticket\": 1, \"ranking_start\": 2}, {\"award_ids\": [51, 88], \"ranking_end\": 20, \"final_ticket\": 1, \"ranking_start\": 4}]', `reward_description` = '积分赛事线上比赛前20名奖励', `created` = 0, `updated` = 0 WHERE `id` = 1;
UPDATE `lucky_game`.`tournament_rewards` SET `round_type` = 0, `rank_start` = 1, `rank_end` = 12, `reward_content` = '[{\"award_ids\": [77], \"ranking_end\": 1, \"ranking_start\": 1}, {\"award_ids\": [78], \"ranking_end\": 2, \"ranking_start\": 2}, {\"award_ids\": [79], \"ranking_end\": 3, \"ranking_start\": 3}, {\"award_ids\": [80], \"ranking_end\": 8, \"ranking_start\": 4}, {\"award_ids\": [81], \"ranking_end\": 12, \"ranking_start\": 9}]', `reward_description` = '线上热身赛每轮前12名奖励', `created` = 0, `updated` = 0 WHERE `id` = 3;
UPDATE `lucky_game`.`tournament_rewards` SET `round_type` = 3, `rank_start` = 1, `rank_end` = 100, `reward_content` = '[{\"award_ids\": [82], \"ranking_end\": 1, \"ranking_start\": 1}, {\"award_ids\": [83], \"ranking_end\": 3, \"ranking_start\": 2}, {\"award_ids\": [84], \"ranking_end\": 10, \"ranking_start\": 4}, {\"award_ids\": [85], \"ranking_end\": 30, \"ranking_start\": 11}]', `reward_description` = '线上热身赛结算前100名奖励', `created` = 0, `updated` = 0 WHERE `id` = 4;

INSERT INTO `lucky_game`.`awards` (`created`, `award_id`, `type`, `level`, `name`, `content`, `updated`) VALUES (0, 77, 6, 11, '5元话费', '{\"rewards\": [{\"img\": \"store/mr_5.png\", \"cost\": 5, \"type\": \"phone_charge\", \"title\": \"5元话费\", \"amount\": 1, \"good_id\": 110, \"describe\": \"面值 5 元，可抵扣手机话费充值金额\", \"good_sku\": \"AHEYRPID\"}]}', 0);
INSERT INTO `lucky_game`.`awards` (`created`, `award_id`, `type`, `level`, `name`, `content`, `updated`) VALUES (0, 78, 6, 12, '1元话费', '{\"rewards\": [{\"img\": \"store/mr_1.png\", \"cost\": 1, \"type\": \"phone_charge\", \"title\": \"1元话费\", \"amount\": 1, \"good_id\": 111, \"describe\": \"面值 1 元，可抵扣手机话费充值金额\", \"good_sku\": \"AHEYRPIE\"}]}', 0);
INSERT INTO `lucky_game`.`awards` (`created`, `award_id`, `type`, `level`, `name`, `content`, `updated`) VALUES (0, 79, 6, 13, '288钻石', '{\"rewards\": [{\"img\": \"store/sc3.png\", \"type\": \"diamond\", \"title\": \"钻石x288\", \"amount\": 288}], \"good_suk\": \"VWRAIABV\"}', 0);
INSERT INTO `lucky_game`.`awards` (`created`, `award_id`, `type`, `level`, `name`, `content`, `updated`) VALUES (0, 80, 6, 14, '188钻石', '{\"rewards\": [{\"img\": \"store/sc3.png\", \"type\": \"diamond\", \"title\": \"钻石x188\", \"amount\": 188}], \"good_suk\": \"VWRBIABV\"}', 0);
INSERT INTO `lucky_game`.`awards` (`created`, `award_id`, `type`, `level`, `name`, `content`, `updated`) VALUES (0, 81, 6, 15, '88钻石', '{\"rewards\": [{\"img\": \"store/sc3.png\", \"type\": \"diamond\", \"title\": \"钻石x88\", \"amount\": 88}], \"good_suk\": \"VWRCIABV\"}', 0);
INSERT INTO `lucky_game`.`awards` (`created`, `award_id`, `type`, `level`, `name`, `content`, `updated`) VALUES (0, 82, 6, 21, '金州风光尊享礼遇', '{\"rewards\": [{\"img\": \"store/cy_ytjd.png\", \"type\": \"scenic_spot\", \"title\": \"云屯公园酒店住宿券\", \"amount\": 1, \"good_id\": 97, \"good_sku\": \"AEEYRPIC\"}, {\"img\": \"tournament/select_3.png\", \"type\": \"scenic_spot_select\", \"title\": \"任选景区门票：万峰林/马岭河峡谷/峰林布依\", \"amount\": 1, \"good_id\": 113, \"good_sku\": \"GFEYRPIC\"}]}', 0);
INSERT INTO `lucky_game`.`awards` (`created`, `award_id`, `type`, `level`, `name`, `content`, `updated`) VALUES (0, 83, 6, 22, '双泉沐云意境体验券', '{\"rewards\": [{\"img\": \"store/cy_ytwq.png\", \"type\": \"scenic_spot\", \"title\": \"云屯公园温泉票\", \"amount\": 2, \"good_id\": 96, \"good_sku\": \"ADEYRPIC\"}]}', 0);
INSERT INTO `lucky_game`.`awards` (`created`, `award_id`, `type`, `level`, `name`, `content`, `updated`) VALUES (0, 84, 6, 23, '金州山水初遇体验券', '{\"rewards\": [{\"img\": \"tournament/select_3.png\", \"type\": \"scenic_spot_select\", \"title\": \"任选景区门票：万峰林/马岭河峡谷/峰林布依\", \"amount\": 1, \"good_id\": 113, \"good_sku\": \"GFEYRPIC\"}]}', 0);
INSERT INTO `lucky_game`.`awards` (`created`, `award_id`, `type`, `level`, `name`, `content`, `updated`) VALUES (0, 85, 6, 24, '云屯轻履休闲体验券', '{\"rewards\": [{\"img\": \"store/cy_ytgy.png\", \"type\": \"scenic_spot\", \"title\": \"云屯公园门票\", \"amount\": 1, \"good_id\": 112, \"good_sku\": \"AFEYRPIC\"}]}', 0);
INSERT INTO `lucky_game`.`awards` (`created`, `award_id`, `type`, `level`, `name`, `content`, `updated`) VALUES (0, 86, 4, 11, '金州之巅·双人奢享礼遇​', '{\"rewards\": [{\"img\": \"store/cy_ytjd.png\", \"type\": \"scenic_spot\", \"title\": \"云屯公园酒店住宿券\", \"amount\": 1, \"good_id\": 97, \"good_sku\": \"AEEYRPIC\"}, {\"img\": \"store/cy_ytwq.png\", \"type\": \"scenic_spot\", \"title\": \"云屯公园温泉票\", \"amount\": 2, \"good_id\": 96, \"good_sku\": \"ADEYRPIC\"}]}', 0);
INSERT INTO `lucky_game`.`awards` (`created`, `award_id`, `type`, `level`, `name`, `content`, `updated`) VALUES (0, 87, 4, 12, '山水秘韵·双人探索礼遇​​', '{\"rewards\": [{\"img\": \"store/cy_ytjd.png\", \"type\": \"scenic_spot\", \"title\": \"峰林布依景区门票\", \"amount\": 2, \"good_id\": 80, \"good_sku\": \"AAEYRPIC\"}, {\"img\": \"store/cy_ytwq.png\", \"type\": \"scenic_spot\", \"title\": \"马岭河峡谷门票\", \"amount\": 2, \"good_id\": 81, \"good_sku\": \"ABEYRPIC\"}]}', 0);
INSERT INTO `lucky_game`.`awards` (`created`, `award_id`, `type`, `level`, `name`, `content`, `updated`) VALUES (0, 88, 4, 13, '金州之巅·双人奢享礼遇​', '{\"rewards\": [{\"img\": \"store/cy_ytwq.png\", \"type\": \"scenic_spot_select\", \"title\": \"任选景区门票：万峰林/马岭河峡谷/峰林布依\", \"amount\": 1, \"good_id\": 113, \"good_sku\": \"GFEYRPIC\"}]}', 0);

INSERT INTO `lucky_game`.`goods` (`created`, `good_id`, `sid`, `kind`, `type`, `currency`, `sku`, `total`, `purchase_limit`, `name`, `img`, `desc`, `original`, `price`, `content`, `status`, `up_time`, `down_time`, `bag_type`, `rank`, `updated`) VALUES (0, 107, 0, 0, 13, 0, 'VWRAIABV', -1, '', '288钻石', 'store/sc3.png', NULL, 288.00, 0.00, '{\"img\": \"store/sc3.png\", \"type\": \"diamond\", \"title\": \"钻石x288\", \"amount\": 288}', 1, NULL, NULL, 0, 1, 0);
INSERT INTO `lucky_game`.`goods` (`created`, `good_id`, `sid`, `kind`, `type`, `currency`, `sku`, `total`, `purchase_limit`, `name`, `img`, `desc`, `original`, `price`, `content`, `status`, `up_time`, `down_time`, `bag_type`, `rank`, `updated`) VALUES (0, 108, 0, 0, 13, 0, 'VWRBIABV', -1, '', '188钻石', 'store/sc3.png', NULL, 188.00, 0.00, '{\"img\": \"store/sc3.png\", \"type\": \"diamond\", \"title\": \"钻石x188\", \"amount\": 188}', 1, NULL, NULL, 0, 2, 0);
INSERT INTO `lucky_game`.`goods` (`created`, `good_id`, `sid`, `kind`, `type`, `currency`, `sku`, `total`, `purchase_limit`, `name`, `img`, `desc`, `original`, `price`, `content`, `status`, `up_time`, `down_time`, `bag_type`, `rank`, `updated`) VALUES (0, 109, 0, 0, 13, 0, 'VWRCIABV', -1, '', '88钻石', 'store/sc3.png', NULL, 88.00, 0.00, '{\"img\": \"store/sc3.png\", \"type\": \"diamond\", \"title\": \"钻石x88\", \"amount\": 88}', 1, NULL, NULL, 0, 3, 0);
INSERT INTO `lucky_game`.`goods` (`created`, `good_id`, `sid`, `kind`, `type`, `currency`, `sku`, `total`, `purchase_limit`, `name`, `img`, `desc`, `original`, `price`, `content`, `status`, `up_time`, `down_time`, `bag_type`, `rank`, `updated`) VALUES (0, 110, 0, 2, 17, 6, 'AHEYRPID', -1, '', '5元话费', 'store/mr_5.png', '', 50.00, 50.00, '{\"img\": \"store/mr_5.png\", \"cost\": 5, \"type\": \"phone_charge\", \"title\": \"5元话费\", \"amount\": 1, \"describe\": \"面值 5 元，可抵扣手机话费充值金额\"}', 1, NULL, NULL, 1, 9, 0);
INSERT INTO `lucky_game`.`goods` (`created`, `good_id`, `sid`, `kind`, `type`, `currency`, `sku`, `total`, `purchase_limit`, `name`, `img`, `desc`, `original`, `price`, `content`, `status`, `up_time`, `down_time`, `bag_type`, `rank`, `updated`) VALUES (0, 111, 0, 2, 17, 6, 'AHEYRPIE', -1, '', '1元话费', 'store/mr_1.png', '', 10.00, 10.00, '{\"img\": \"store/mr_1.png\", \"cost\": 1, \"type\": \"phone_charge\", \"title\": \"1元话费\", \"amount\": 1, \"describe\": \"面值 1 元，可抵扣手机话费充值金额\"}', 1, NULL, NULL, 1, 9, 0);
INSERT INTO `lucky_game`.`goods` (`created`, `good_id`, `sid`, `kind`, `type`, `currency`, `sku`, `total`, `purchase_limit`, `name`, `img`, `desc`, `original`, `price`, `content`, `status`, `up_time`, `down_time`, `bag_type`, `rank`, `updated`) VALUES (0, 112, 0, 1, 18, 6, 'AFEYRPIC', -1, '', '云屯公园门票', 'store/cy_ytgy.png', '', 0.00, 0.00, '{\"img\": \"store/cy_ytgy.png\", \"type\": \"scenic_spot\", \"title\": \"云屯公园门票\", \"amount\": 1, \"describe\": \"云屯公园景区游玩\"}', 1, NULL, NULL, 1, 6, 0);
INSERT INTO `lucky_game`.`goods` (`created`, `good_id`, `sid`, `kind`, `type`, `currency`, `sku`, `total`, `purchase_limit`, `name`, `img`, `desc`, `original`, `price`, `content`, `status`, `up_time`, `down_time`, `bag_type`, `rank`, `updated`) VALUES (0, 113, 0, 1, 18, 6, 'GFEYRPIC', -1, '', '任选景区门票', 'tournament/select_3.png', '', 0.00, 0.00, '{\"img\": \"tournament/select_3.png\", \"type\": \"scenic_spot_select\", \"title\": \"任选景区门票：万峰林/马岭河峡谷/峰林布依）\", \"amount\": 1, \"describe\": \"游玩任意景区\"}', 1, NULL, NULL, 1, 7, 0);

UPDATE `lucky_game`.`goods` SET `created` = 0, `sid` = 0, `kind` = 1, `type` = 18, `currency` = 6, `sku` = 'AAEYRPIC', `total` = -1, `purchase_limit` = '', `name` = '峰林布依景区门票', `img` = 'store/cy_flby.png', `desc` = '', `original` = 700.00, `price` = 700.00, `content` = '{\"img\": \"store/cy_flby.png\", \"type\": \"scenic_spot\", \"title\": \"峰林布依景区门票\", \"amount\": 1, \"describe\": \"热门景区入园凭证，畅游布依特色风光\"}', `status` = 1, `up_time` = NULL, `down_time` = NULL, `bag_type` = 1, `rank` = 9, `updated` = 0 WHERE `good_id` = 80;
UPDATE `lucky_game`.`goods` SET `created` = 0, `sid` = 0, `kind` = 1, `type` = 18, `currency` = 6, `sku` = 'ABEYRPIC', `total` = -1, `purchase_limit` = '', `name` = '马岭河峡谷景区门票', `img` = 'store/cy_mlh.png', `desc` = '', `original` = 700.00, `price` = 700.00, `content` = '{\"img\": \"store/cy_mlh.png\", \"type\": \"scenic_spot\", \"title\": \"马岭河峡谷景区门票\", \"amount\": 1, \"describe\": \"热门景区入园凭证，畅游布依特色风光\"}', `status` = 1, `up_time` = NULL, `down_time` = NULL, `bag_type` = 1, `rank` = 8, `updated` = 0 WHERE `good_id` = 81;
UPDATE `lucky_game`.`goods` SET `created` = 0, `sid` = 0, `kind` = 1, `type` = 18, `currency` = 6, `sku` = 'ACEYRPIC', `total` = -1, `purchase_limit` = '', `name` = '万峰林景区门票', `img` = 'store/cy_wfl.png', `desc` = '', `original` = 900.00, `price` = 900.00, `content` = '{\"img\": \"store/cy_wfl.png\", \"type\": \"scenic_spot\", \"title\": \"万峰林景区门票\", \"amount\": 1, \"describe\": \"热门景区入园凭证，尽赏峰林壮阔景观\"}', `status` = 1, `up_time` = NULL, `down_time` = NULL, `bag_type` = 1, `rank` = 7, `updated` = 0 WHERE `good_id` = 95;
UPDATE `lucky_game`.`goods` SET `created` = 0, `sid` = 0, `kind` = 1, `type` = 18, `currency` = 6, `sku` = 'ADEYRPIC', `total` = -1, `purchase_limit` = '', `name` = '云屯沐云温泉票', `img` = 'store/cy_ytwq.png', `desc` = '', `original` = 1980.00, `price` = 1980.00, `content` = '{\"img\": \"store/cy_ytwq.png\", \"type\": \"scenic_spot\", \"title\": \"云屯沐云温泉票\", \"amount\": 1, \"describe\": \"轻奢温泉体验票，享受舒适泡汤时光\"}', `status` = 1, `up_time` = NULL, `down_time` = NULL, `bag_type` = 1, `rank` = 6, `updated` = 0 WHERE `good_id` = 96;
UPDATE `lucky_game`.`goods` SET `created` = 0, `sid` = 0, `kind` = 1, `type` = 18, `currency` = 6, `sku` = 'AEEYRPIC', `total` = -1, `purchase_limit` = '', `name` = '云屯沐云高级房一晚', `img` = 'store/cy_ytjd.png', `desc` = '', `original` = 9800.00, `price` = 9800.00, `content` = '{\"img\": \"store/cy_ytjd.png\", \"type\": \"scenic_spot\", \"title\": \"云屯沐云高级房一晚\", \"amount\": 1, \"describe\": \"高端住宿体验，入住舒适高级客房一晚\"}', `status` = 1, `up_time` = NULL, `down_time` = NULL, `bag_type` = 1, `rank` = 5, `updated` = 0 WHERE `good_id` = 97;

UPDATE `lucky_game`.`stores` SET `created` = 0, `platform` = '1,2,3,7,8', `type` = 17, `currency` = 6, `rank` = 9, `purchase_limit` = '', `name` = '福袋', `img` = '', `desc` = '福袋兑换商城', `status` = 0, `start_time` = NULL, `end_time` = NULL, `updated` = 0 WHERE `sid` = 10;
