CREATE TABLE `game_rooms` (
  `created` bigint DEFAULT '0' COMMENT '创建时间',
  `id` int NOT NULL AUTO_INCREMENT COMMENT '房间ID',
  `club_id` int NOT NULL DEFAULT '0' COMMENT '茶馆ID,无茶馆为0',
  `creator` int DEFAULT NULL COMMENT '房主ID(玩家ID)',
  `platform` smallint DEFAULT NULL COMMENT '平台: 1微信小游戏 2APP 3H5',
  `rule_details` json DEFAULT NULL COMMENT '房间玩法规则：JSON存储',
  `max_player` smallint DEFAULT '0' COMMENT '最大人数',
  `status` smallint NOT NULL DEFAULT '0' COMMENT '房间状态',
  `updated` bigint DEFAULT '0' COMMENT '更新时间',
  `play_type` smallint NOT NULL DEFAULT '1' COMMENT '玩法类型',
  `cs_type` int NOT NULL DEFAULT '0' COMMENT '子服务类型',
  `room_id` int NOT NULL COMMENT '房间ID',
  `pay_type` smallint DEFAULT '0' COMMENT '支付方式：0房主 1冠军支付 2茶馆基金 3AA支付',
  `price` smallint DEFAULT '0' COMMENT '费用',
  `total_round` smallint DEFAULT '0' COMMENT '总局数',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_game_rooms_room_id_95442f` (`room_id`) USING BTREE,
  KEY `idx_game_rooms_created_e05769` (`created`),
  KEY `idx_game_rooms_club_id_a0eafe` (`club_id`),
  KEY `idx_game_rooms_status_099223` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='游戏房间关系表';