# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: http_login.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'http_login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10http_login.proto\x12\nhttp.login\x1a\x0c\x63ommon.proto\"\xda\x02\n\x06Person\x12\x0f\n\x07\x63reated\x18\x01 \x01(\r\x12\x0b\n\x03uid\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x1d\n\x03sex\x18\x04 \x01(\x0e\x32\x10.http.common.Sex\x12\r\n\x05phone\x18\x05 \x01(\t\x12\r\n\x05\x65mail\x18\x06 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x07 \x01(\t\x12\x0f\n\x07id_card\x18\x08 \x01(\t\x12\x0c\n\x04gold\x18\t \x01(\t\x12\x0f\n\x07\x64iamond\x18\n \x01(\r\x12\x0e\n\x06\x61vatar\x18\x0b \x01(\t\x12\x0f\n\x07updated\x18\x0c \x01(\r\x12\x11\n\tdev_ident\x18\r \x01(\t\x12\x11\n\tvalid_key\x18\x0e \x01(\t\x12\x10\n\x08new_user\x18\x0f \x01(\x08\x12\n\n\x02ip\x18\x10 \x01(\t\x12\x0e\n\x06region\x18\x11 \x01(\t\x12\r\n\x05token\x18\x12 \x01(\t\x12\x0f\n\x07open_id\x18\x14 \x01(\t\x12\x11\n\tvip_level\x18\x13 \x01(\x05\"b\n\nServerAddr\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07\x63reated\x18\x02 \x01(\r\x12\x0b\n\x03sid\x18\x03 \x01(\r\x12\x0c\n\x04\x61\x64\x64r\x18\x04 \x01(\t\x12\x0c\n\x04path\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\r\"^\n\x08S2CLogin\x12%\n\tuser_info\x18\x01 \x01(\x0b\x32\x12.http.login.Person\x12+\n\x0bserver_info\x18\x02 \x03(\x0b\x32\x16.http.login.ServerAddr\"4\n\x11S2CExternalReturn\x12\x0f\n\x07\x65rrcode\x18\x01 \x01(\x11\x12\x0e\n\x06\x65rrmsg\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'http_login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSON']._serialized_start=47
  _globals['_PERSON']._serialized_end=393
  _globals['_SERVERADDR']._serialized_start=395
  _globals['_SERVERADDR']._serialized_end=493
  _globals['_S2CLOGIN']._serialized_start=495
  _globals['_S2CLOGIN']._serialized_end=589
  _globals['_S2CEXTERNALRETURN']._serialized_start=591
  _globals['_S2CEXTERNALRETURN']._serialized_end=643
# @@protoc_insertion_point(module_scope)
