# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ws_base.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'ws_base.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import any_pb2 as any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rws_base.proto\x12\x07ws.base\x1a\tany.proto\"i\n\tS2CWsBase\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x11\x12\'\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x88\x01\x01\x12\x0c\n\x04hint\x18\x03 \x01(\t\x12\x0e\n\x06req_id\x18\x04 \x01(\tB\x07\n\x05_data\"\"\n\x0cS2CAuthToken\x12\x12\n\nauth_token\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ws_base_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_S2CWSBASE']._serialized_start=37
  _globals['_S2CWSBASE']._serialized_end=142
  _globals['_S2CAUTHTOKEN']._serialized_start=144
  _globals['_S2CAUTHTOKEN']._serialized_end=178
# @@protoc_insertion_point(module_scope)
