# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ws_client.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'ws_client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fws_client.proto\x12\tws.client\"\xa4\x01\n\rAgainRoomInfo\x12\x0f\n\x07room_id\x18\x01 \x01(\r\x12\x11\n\tplay_type\x18\x02 \x01(\r\x12\x0f\n\x07\x63s_type\x18\x03 \x01(\r\x12\x0f\n\x07\x63reator\x18\x04 \x01(\r\x12\x0e\n\x06status\x18\x05 \x01(\r\x12\x13\n\x0btotal_round\x18\x06 \x01(\r\x12\x12\n\nmax_player\x18\x07 \x01(\r\x12\x14\n\x0crule_details\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ws_client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGAINROOMINFO']._serialized_start=31
  _globals['_AGAINROOMINFO']._serialized_end=195
# @@protoc_insertion_point(module_scope)
